general_cfg:
  algo_name: DQN_new # algo name
  device: cpu # device, cpu or cuda
  env_name: gym # env name, differ from env_id in env_cfgs
  mode: train # run mode: train, test
  mp_backend: null # multi-processing mode: null(default), ray
  n_workers: 1 # number of workers if using multi-processing, default 1
  load_checkpoint: false # if load checkpoint or not
  load_path: Train_CartPole-v1_DQN_20221026-054757 # if load checkpoint, then config path in 'tasks' dir
  max_episode: 100 # max episodes, set -1 to keep running
  max_step: 200 # max steps per episode
  seed: 1 # random seed, set 0 not to use seed
  save_fig: true # if save fig or not
  show_fig: false # if show fig or not
  test_eps: 10
algo_cfg:
  value_layers:
    - layer_type: linear
      layer_dim: [256]
      activation: relu
    - layer_type: linear
      layer_dim: [256]
      activation: relu
  batch_size: 64
  buffer_type: REPLAY_QUE
  buffer_size: 100000
  epsilon_decay: 500
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.95
  lr: 0.0001
  target_update: 4
env_cfg:
  id: CartPole-v1
  render_mode: null