general_cfg:
  algo_name: DQN_new
  device: cpu
  env_name: gym
  mode: train
  mp_backend: ray 
  n_workers: 1
  load_checkpoint: false
  load_path: Train_CartPole-v1_DQN_20221026-054757
  max_step: 200
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  max_epsiode: 200
algo_cfg:
  value_layers:
    - layer_type: linear
      layer_dim: [256]
      activation: relu
    - layer_type: linear
      layer_dim: [256]
      activation: relu
  batch_size: 64
  buffer_type: REPLAY_QUE
  buffer_size: 100000
  epsilon_decay: 500
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.95
  lr: 0.0001
  target_update: 4
env_cfg:
  id: CartPole-v1
  new_step_api: true
  render_mode: null