general_cfg:
  algo_name: TD3
  device: cpu
  env_name: gym
  eval_eps: 10
  eval_per_episode: 50
  load_checkpoint: true
  load_path: Train_BipedalWalkerHardcore-v3_TD3_20230506-003018
  max_steps: 1000
  mode: test
  mp_backend: mp
  n_workers: 1
  new_step_api: true
  render: true
  render_mode: rgb_array
  save_fig: true
  seed: 2023
  show_fig: false
  test_eps: 2
  train_eps: 1000
  wrapper: null
algo_cfg:
  actor_hidden_dim: 200
  actor_lr: 0.0001
  batch_size: 256
  buffer_size: 60000
  critic_hidden_dim: 200
  critic_lr: 0.00012
  expl_noise: 0.25
  explore_steps: 2048
  gamma: 0.99
  global_best_reward: -1800
  noise_clip: 0.5
  policy_freq: 2
  policy_noise: 0.2
  tau: 0.005
env_cfg:
  id: BipedalWalkerHardcore-v3
  ignore_params:
  - wrapper
  - ignore_params
  new_step_api: true
  render_mode: rgb_array
  wrapper: null
