general_cfg:
  algo_name: SAC_D
  continous: true
  device: cpu
  env_name: gym
  eval_eps: 10
  eval_per_episode: 5
  load_checkpoint: true
  load_path: Train_gym_SAC_D_20230427-130926
  max_steps: 200
  mode: test
  mp_backend: mp
  new_step_api: true
  render: true
  render_mode: rgb_array
  save_fig: true
  seed: 0
  show_fig: false
  test_eps: 200
  train_eps: 1000
  wrapper: null
algo_cfg:
  alpha: 0.1
  automatic_entropy_tuning: false
  batch_size: 64
  buffer_size: 1000000
  epsilon_decay: 500
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.99
  hidden_dim: 256
  lr: 0.001
  n_epochs: 1
  target_update: 1
  tau: 0.005
env_cfg:
  id: Acrobot-v1
  new_step_api: true
  render_mode: null
