general_cfg:
  algo_name: SAC
  device: cuda
  env_name: gym
  eval_eps: 10
  eval_per_episode: 5
  load_checkpoint: true
  load_path: Train_Ant-v4_SAC_20230426-134747
  max_steps: 200
  mode: test
  mp_backend: mp
  n_workers: 1
  new_step_api: true
  render: false
  render_mode: rgb_array
  save_fig: true
  seed: 0
  show_fig: false
  test_eps: 200
  train_eps: 1000
  wrapper: true
algo_cfg:
  alpha: 0.1
  automatic_entropy_tuning: false
  batch_size: 64
  buffer_size: 1000000
  continous: true
  gamma: 0.99
  hidden_dim: 64
  lr: 0.001
  n_actions: 8
  n_epochs: 1
  n_states: 27
  policy_type: Gaussian
  start_steps: 10000
  target_update_fre: 1
  tau: 0.005
env_cfg:
  id: Ant-v4
  ignore_params:
  - wrapper
  - ignore_params
  new_step_api: true
  render_mode: null
  wrapper: null
